sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alias:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: ye-java
    region: cn-beijing

  redis:
    host: localhost
    port: 6379
    database: 1

  wechat:
    appid: wx915491def729d4cc
    secret: 91b760e2fe0862bd46493a7e78fa5cae
